apiVersion: v1
kind: Service
metadata:
  name: rckg-dapp-staking-fe
  namespace: {{namespace}}
  labels:
    app: rckg-dapp-staking-fe
spec:
  selector:
    app: rckg-dapp-staking-fe
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rckg-dapp-staking-fe
  namespace: {{namespace}}
  labels:
    app: rckg-dapp-staking-fe
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: rckg-dapp-staking-fe
  template:
    metadata:
      labels:
        app: rckg-dapp-staking-fe
    spec:
      containers:
        - name: rckg-dapp-staking-fe
          image: {{image}}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP